#!/bin/bash

# Factorial of a number  <-- This comment seems incorrect for Fibonacci; let's update it
# Fibonacci sequence up to n terms

echo -n "Enter the number of terms: "
read num

a=0
b=1

echo -n "$a "
echo -n "$b "

i=2  # We already printed first two terms

while [ $i -lt $num ]
do
  c=$((a + b))
  echo -n "$c "
  a=$b
  b=$c
  i=$((i + 1))
done

echo  # for newline after printing sequence




#!/bin/bash

echo -n "Enter a number: "
read num

i=1
fact=1

while [ $i -le $num ]
do
  fact=$((fact * i))
  i=$((i + 1))
done

echo "Factorial of $num is $fact"
